### ISSUE TITLE
Flagging tweaks unreadable with a dark theme

### ISSUE THREAD

**Issue by Aralun** [BrockA/SE-misc#2]
Using the following theme: https://userstyles.org/styles/35345/stackoverflow-dark

This is what the flagging page looks like without the script:

![Screenshot of page without script with dark theme](https://cloud.githubusercontent.com/assets/4149052/20973923/bf1600cc-bc9a-11e6-9944-32a1acec4bb4.png)

And with the script:

![Screenshot of page without script with dark theme](https://cloud.githubusercontent.com/assets/4149052/20974101/6c221c4c-bc9b-11e6-8bde-227550040331.png)

As such, it's unreadable.

If I can find some time in the following weeks I'll fork and fix it, then PR (use a new file?). It should be a matter of changing a couple lines of CSS.

**Comment by BrockA** [comment]
Ugh, I _hate_ dark themes and am not super-inclined to support them.
Nevertheless, if you just:

1. Use your browser to edit the colors like you like them.

**Comment by BrockA** [comment]
Ugh, I _hate_ dark themes and am not super-inclined to support them.
Nevertheless, if you just:

1. Use your browser to temporarily edit the colors like you like them, on one page.
1. Write down each changed color value. EG:  `pink`, `#08ff11`, etc.
1. Take a screen shot of the result.
1. Attach the screen shot and color list here.

Then it _should_ be fairly quick and easy for me to add an alternate style to the script.

**Comment by BrockA** [comment]
@Aralun, I'm closing for now, due to lack of interest.  Provide the requested information, and I will address it.
Regards,
Brock
